apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: uday-fault-injection-reviews
spec:
  hosts:
    - reviews
  http:
    - match:
        - headers:
            fault-enabled:
              exact: "true"
      fault:
        delay:
          percentage:
            value: 50.0
          fixedDelay: 5s
        abort:
          percentage:
            value: 10.0
          httpStatus: 500
      route:
        - destination:
            host: reviews
            subset: v1